### ISSUE TITLE
BMA421 work in interrupt-driven mode

### ISSUE THREAD

**Issue by ck-telecom** [ck-telecom/pinetime#2]
Now the bma421 driver could poll data from, but can not in interrupt-driven mode to save more power

**Comment by StarGate01** [comment]
Hi! Did you manage to get the hardware interrupt working?

**Comment by ck-telecom** [comment]
I tried on my another watch which is bma423, everything is well, but I am not sure bma421 is not a public version chip, that is worth to try

**Comment by StarGate01** [comment]
It might be not possible on a hardware level on the BMA321,its product brief (http://static6.arrow.com/aropdfconversion/ad8392ae5860726c75b2a425eebd94416f860baa/25bma421_productflyer_bst_20170328.pdf) states:

> Embedded Intelligence:
> Step detector / Step counting
> Any-motion/No-motion

whereas the BMA422 brief (https://www.bosch-sensortec.com/media/boschsensortec/downloads/product_flyer/bst-bma422-fl000.pdf) states:

> Embedded Intelligence:
> Step detector / Step counting
> Significant motion
> Tilt detection
> Wake-up, Glance, Pick-up

and finally, the "wearables feature set" (https://www.bosch-sensortec.com/media/boschsensortec/downloads/application_notes_1/bst-mas-an032-00.pdf), which applies to "BMA423, BMA425, BMA456" supports

> Single-tap
> Step detector
> Activity recognition
> Wrist wear wakeup
> Double-tap
> Any-motion
> No-motion
> Error Interrupt

The driver code for the BMA421 in InfiniTime is based on the public BMA423 repo by Bosch. So I guess even though interrupts on the BMA421 could work in theory, the interrupt sources are rather limited. My main interest would be on tap detection, but that  seems to be unavailable in hardware.

**Comment by ck-telecom** [comment]
I have look at interrupt bitmaskt is not same as bma423, so the interrupt source code maybe is not suitable for bma421, just need some modifications

**Comment by ck-telecom** [comment]
I will try based on `drivers/sensor/bma421/libbma421/` to see the result, not sure the config file correct because is not the same with bma423 modified by InfiniTime

**Comment by StarGate01** [comment]
Thanks for the tip, I plan to compare your implementation against the InfiniTime one to see what differences there are in the register configurations. I can't say when I have time to continue, but I'll report back if I get it working.

**Comment by ck-telecom** [comment]
I will reference on my bma423 code which is successfully work with interrupt driven same as Zephyr driver

**Comment by ck-telecom** [comment]
The data ready interrupt work now, will try step counter later

**Comment by sdorre** [comment]
Just my grain of salt in here: 
BMA421 is a closed component. It needs a binary sequence to be uploaded during the initialisation to work properly. (At least to get the step counter working)
So Either you actually contact Bosch and sign a NDA with them to get the actual binary... Or you dig a bit the internet to find out that people already did a bit a retro engineering and got a binary that seems to work (I would look into the micro python FW of the pinetime ;) ) 
But Either way. You won't be allowed to upstream that driver to Zephyr..

**Comment by StarGate01** [comment]
@sdorre Both the micropython based wasp-os driver (https://github.com/daniel-thompson/bma42x-upy/blob/master/BMA42X-Sensor-API/bma421_config.h#L8=) as well as InfiniTime (https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/src/drivers/Bma421_C/bma423.c#L561=, which is what I work with) already use the reverse engineered config blob (I suppose by https://gist.github.com/atc1441/788b5320050f50d65f71338e6e89c224), in order to get step counting working properly.

The question remains is what interrupt events the BMA421 is able to generate, and whether these events can be mapped to the actual hardware pin. I found various opinions on what the chip is exactly capable of, and the ability to generate interrupts might be enabled / disabled in the config blob.

**Comment by ck-telecom** [comment]
now I am using  (https://github.com/daniel-thompson/bma42x-upy/blob/master/BMA42X-Sensor-API/bma421_config.h#L8=) it could generate data ready interrupt

**Comment by StarGate01** [comment]
Thank you for the testing, this helps me a lot. I still suspect that the BMA421 cannot detect complex motion events, e.g. double taps, on a hardware level.

**Comment by sdorre** [comment]
No the BMA421 is limited to :
- Step count 
- step detection
- Any/No motions

Look at the datasheet
https://pdf1.alldatasheet.com/datasheet-pdf/view/1137426/BOSCH/BMA421.html

But the Touchscreen can do double tap ;-)

**Comment by ck-telecom** [comment]
@sdorre Do you still have interesting in Zephyr pinetime firmware, I have almost finished the basic component(basic drivers includeing SPI Nor flash, vibration, bma421 etc), and focus on pebble event API implementation that need help!
