### ISSUE TITLE
West build fails

### ISSUE THREAD

**Issue by paulcockrell** [ck-telecom/pinetime#4]
**Great to see you have kept the Hypnos project going!**

Running `west build` fails with the following error

`devicetree error: missing data after phandle in <Property 'pwms' at '/pwmleds/pwm_led_0' in '/home/operator/Development/pine-time/pinetime-zephyr/zephyr/misc/empty_file.c'>`

To get the build working I updated pinetime_devkit0.overlay with the following, but I think its not correct as the backlight never turns on :-)

```
pwm_led0: pwm_led_0 {
                       pwms = <&pwm0 23 PWM_MSEC(20) PWM_POLARITY_NORMAL>;
```

**Comment by ck-telecom** [comment]
fixed
https://github.com/ck-telecom/pinetime/commit/8635d78b2f495a1ad4f61f95fd5ffb275b4d132a
